version: '3.1'

services:
  app:
    image: mcr.microsoft.com/dotnet/core/runtime
    environment:
      - "LSS_LOG_FILE=true"
      - "TERM=xterm-256color"
    volumes:
      - ".:/app"
    devices:
      - "/dev/gpiomem"
    working_dir: "/app"
    command: "./LightSourceSearch"